### ISSUE TITLE
mycat集成测试出现多表关联不支持

### ISSUE THREAD

**Issue by lujunGit** [jt-20180528/pro_document#1]
2018-07-05 18:21:00,197 [DESKTOP-1LO98I2-20881] [] [] [Thread-32356] ERROR druid.sql.Statement - {conn-10006, pstmt-23810} execute error. UPDATE t_bet_order as b INNER JOIN t_bet_order_data as td ON b.id=td.id and td.Lottery_number_id=?  SET b.WIN_STATUS=td.win_status, b.LOTTERY_NUMBER=td.LOTTERY_NUMBER,b.odds=td.odds,b.WIN_AMOUNT=td.win_amount,b.WIN_SECRET=td.win_secret,b.WIN_COUNT=td.win_count 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: multi table related update not supported,tables:[T_BET_ORDER_DATA, T_BET_ORDER]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

**Comment by lujunGit** [comment]
需要在mycat中配置全局表，用来关联查询，否则mycat不识别，现在已经配置了全局表，解决了这个问题。
