### ISSUE TITLE
mycat集成测试多表关联导致派奖异常的问题

### ISSUE THREAD

**Issue by lujunGit** [jt-20180528/pro_document#2]
2018-07-05 18:21:00,208 [DESKTOP-1LO98I2-20881] [] [] [Thread-32356] ERROR com.hitler.lottery.event.AwardEvent - [开奖:47,20180705-1101,111101]派奖异常！！！^M
org.springframework.dao.InvalidDataAccessResourceUsageException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not execute statement^M
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:242)^M
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225)^M
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:

**Comment by lujunGit** [comment]
已经解决，目前是分库分表场景，解决了这个问题
