### ISSUE TITLE
项目运行期间jbdc连接突然关闭

### ISSUE THREAD

**Issue by lujunGit** [jt-20180528/pro_document#21]
2018-07-25 02:49:10,295 [DESKTOP-1LO98I2-20881] [] [] [pool-3-thread-423] ERROR com.alibaba.druid.util.JdbcUtils - close connection error^M
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Communications link failure during rollback(). Transaction resolution unknown.^M
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)^M
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)^M
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)^M
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by lujunGit** [comment]
目前在做读写分离测试中也发现了同样的问题，关联问题 #33  中的问题2

**Comment by lujunGit** [comment]
已经解决，原因是，jtPay方法使用了jap自带的方式修改数据，jpa的数据连接对象使用的是内部缓存的对象，此方法又是异步的，而driud数据库连接池的对象有租期时间，时间到了会自动关闭，缓存对象没有关闭，导致出现连接失败。
