### ISSUE TITLE
mycat连接正常突然出现拒绝连接

### ISSUE THREAD

**Issue by lujunGit** [jt-20180528/pro_document#6]
80705-1118,yc1578]投注总耗时：188 ms^M
2018-07-05 18:37:40,984 [DESKTOP-1LO98I2-20881] [] [] [pool-3-thread-7] INFO  com.hitler.service.bet.BetOrderService - [投注,CT,47,20180705-1118,yc1578]投注成功！^M
2018-07-05 18:37:50,184 [DESKTOP-1LO98I2-20881] [] [] [DubboServerHandler-10.212.134.200:20881-thread-707] ERROR druid.sql.Statement - {conn-10032, pstmt-28389} execute error. select t.* from t_tenant t,t_tenant_game g where t.TENANT_CODE = g.TENANT_CODE and g.GAME_ID = ? and t.ENABLED = ?^M
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: 拒绝连接^M
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)^M
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)^M
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

**Comment by lujunGit** [comment]
检查发现这个sql是开奖的sql在定时任务中，执行频次很高，所以可能前几次执行已经关闭，但是后来再次执行则发现事务已经提交，不排除是缓存的作用，导致无法提交事务，拒绝连接，现在在连接url中添加参数autoReconnect=true之后测试一切正常，暂未发现问题。
