### ISSUE TITLE
mycat连接holder为空

### ISSUE THREAD

**Issue by lujunGit** [jt-20180528/pro_document#8]
Caused by: java.sql.SQLException: connection holder is null^M
        at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1155)^M
        at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1148)^M
        at com.alibaba.druid.pool.DruidPooledConnection.getAutoCommit(DruidPooledConnection.java:736)^M
        at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.isAutoCommit(LogicalConnectionImpl.java:322)^M
        ... 73 common frames omitted^M
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: 拒绝连接^M
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)^M
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)^

**Comment by lujunGit** [comment]
已解决，参考： #4 #6
